/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectovisual.gProductos;

import fiuni.edu.py.Controladores.ControladorProducto;

/**
 *
 * @author luisf
 */
public class ProductoBuscado extends javax.swing.JFrame {
    int id;
    ControladorProducto controlador= new ControladorProducto();
    /**
     * Creates new form MenuPrincipal
     */
    public ProductoBuscado(int id) {
        this.id=id;
        initComponents();
        setLocationRelativeTo(null);
        cargarDatos();
    }
    public ProductoBuscado() {
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(220, 220, 180));
        setMinimumSize(new java.awt.Dimension(640, 420));
        getContentPane().setLayout(new java.awt.BorderLayout(5, 0));

        jPanel1.setBackground(new java.awt.Color(220, 220, 180));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 112));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jSeparator3.setForeground(java.awt.Color.darkGray);
        jSeparator3.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel1.add(jSeparator3);

        jPanel3.setBackground(new java.awt.Color(220, 220, 180));
        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator9.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator9.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator9.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel3.add(jSeparator9);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre del Producto");
        jPanel3.add(jLabel2);

        jSeparator12.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator12.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator12.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel3.add(jSeparator12);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(220, 220, 180));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setMaximumSize(new java.awt.Dimension(600, 40));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator10.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator10.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator10.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel4.add(jSeparator10);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre");
        jPanel4.add(jLabel1);

        jPanel1.add(jPanel4);

        jSeparator4.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator4.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator4.setMaximumSize(new java.awt.Dimension(32767, 10));
        jPanel1.add(jSeparator4);

        jPanel5.setBackground(new java.awt.Color(220, 220, 180));
        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator11.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator11.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator11.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel5.add(jSeparator11);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Precio del Producto");
        jPanel5.add(jLabel3);

        jSeparator13.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator13.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator13.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel5.add(jSeparator13);

        jPanel1.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(220, 220, 180));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setMaximumSize(new java.awt.Dimension(600, 40));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator14.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator14.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator14.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel6.add(jSeparator14);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Precio");
        jPanel6.add(jLabel6);

        jPanel1.add(jPanel6);

        jSeparator5.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator5.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator5.setMaximumSize(new java.awt.Dimension(32767, 10));
        jPanel1.add(jSeparator5);

        jPanel7.setBackground(new java.awt.Color(220, 220, 180));
        jPanel7.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator15.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator15.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator15.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel7.add(jSeparator15);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Stock del Producto");
        jPanel7.add(jLabel4);

        jSeparator16.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator16.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator16.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel7.add(jSeparator16);

        jPanel1.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(220, 220, 180));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setMaximumSize(new java.awt.Dimension(600, 40));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator17.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator17.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator17.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel8.add(jSeparator17);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Stock");
        jPanel8.add(jLabel7);

        jPanel1.add(jPanel8);

        jSeparator6.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator6.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator6.setMaximumSize(new java.awt.Dimension(32767, 10));
        jPanel1.add(jSeparator6);

        jPanel10.setBackground(new java.awt.Color(220, 220, 180));
        jPanel10.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator19.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator19.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator19.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel10.add(jSeparator19);

        jSeparator20.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator20.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator20.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel10.add(jSeparator20);

        jPanel1.add(jPanel10);

        jSeparator7.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator7.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator7.setMaximumSize(new java.awt.Dimension(32767, 10));
        jPanel1.add(jSeparator7);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("VOLVER");
        jButton2.setAlignmentX(0.5F);
        jButton2.setAlignmentY(1.0F);
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(200, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cargarDatos(){
        jLabel1.setText(String.valueOf(controlador.getNombre(id)));
        jLabel6.setText(String.valueOf(controlador.getPrecio(id)));
        if( controlador.getPeso(id)!=-1){
        jLabel7.setText(String.valueOf(controlador.getPeso(id)));
        }
        else{
            jLabel7.setText(String.valueOf(controlador.getUnidades(id)));
        }
        
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new MenuGestionProductos().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoBuscado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
