/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectovisual.gVentas;

import com.mycompany.proyectovisual.gClientes.*;
import com.mycompany.proyectovisual.gProductos.*;
import javax.swing.JOptionPane;
import fiuni.edu.py.Controladores.ControladorClientes;
import fiuni.edu.py.Modelo.Clientes;
import fiuni.edu.py.Repositorios.RepositorioClientes;
/**
 *
 * @author luisf
 */
public class AgregarVenta extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuPrincipal
     */
    public AgregarVenta() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        seccionFechaCliente = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jPanel13 = new javax.swing.JPanel();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jPanel14 = new javax.swing.JPanel();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator28 = new javax.swing.JSeparator();
        jPanel15 = new javax.swing.JPanel();
        jSeparator29 = new javax.swing.JSeparator();
        jTextField6 = new javax.swing.JTextField();
        jSeparator30 = new javax.swing.JSeparator();
        jPanel16 = new javax.swing.JPanel();
        jSeparator31 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator32 = new javax.swing.JSeparator();
        jPanel17 = new javax.swing.JPanel();
        jSeparator33 = new javax.swing.JSeparator();
        jTextField7 = new javax.swing.JTextField();
        jSeparator34 = new javax.swing.JSeparator();
        jPanel18 = new javax.swing.JPanel();
        jSeparator35 = new javax.swing.JSeparator();
        jSeparator36 = new javax.swing.JSeparator();
        jSeparator40 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        seccionCarritoCompras = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jSeparator14 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jSeparator17 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jSeparator37 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(220, 220, 180));
        setMinimumSize(new java.awt.Dimension(640, 420));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        seccionFechaCliente.setBackground(new java.awt.Color(220, 220, 180));
        seccionFechaCliente.setMaximumSize(new java.awt.Dimension(640, 420));
        seccionFechaCliente.setMinimumSize(new java.awt.Dimension(640, 420));
        seccionFechaCliente.setPreferredSize(new java.awt.Dimension(640, 420));
        seccionFechaCliente.setLayout(new javax.swing.BoxLayout(seccionFechaCliente, javax.swing.BoxLayout.Y_AXIS));

        jSeparator8.setForeground(java.awt.Color.darkGray);
        jSeparator8.setMaximumSize(new java.awt.Dimension(32767, 20));
        seccionFechaCliente.add(jSeparator8);

        jPanel9.setBackground(new java.awt.Color(220, 220, 180));
        jPanel9.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator18.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator18.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator18.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel9.add(jSeparator18);

        jSeparator21.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator21.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator21.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel9.add(jSeparator21);

        seccionFechaCliente.add(jPanel9);

        jPanel13.setBackground(new java.awt.Color(220, 220, 180));
        jPanel13.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator25.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator25.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator25.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel13.add(jSeparator25);

        seccionFechaCliente.add(jPanel13);

        jSeparator26.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator26.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator26.setMaximumSize(new java.awt.Dimension(32767, 10));
        seccionFechaCliente.add(jSeparator26);

        jPanel14.setBackground(new java.awt.Color(220, 220, 180));
        jPanel14.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator27.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator27.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator27.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel14.add(jSeparator27);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Ingrese el número de CI del Cliente");
        jPanel14.add(jLabel7);

        jSeparator28.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator28.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator28.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel14.add(jSeparator28);

        seccionFechaCliente.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(220, 220, 180));
        jPanel15.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator29.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator29.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator29.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel15.add(jSeparator29);

        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setForeground(new java.awt.Color(0, 0, 0));
        jTextField6.setText("Ingrese el texto aquí");
        jTextField6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField6.setMaximumSize(new java.awt.Dimension(500, 40));
        jTextField6.setPreferredSize(new java.awt.Dimension(50, 26));
        jPanel15.add(jTextField6);

        seccionFechaCliente.add(jPanel15);

        jSeparator30.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator30.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator30.setMaximumSize(new java.awt.Dimension(32767, 10));
        seccionFechaCliente.add(jSeparator30);

        jPanel16.setBackground(new java.awt.Color(220, 220, 180));
        jPanel16.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator31.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator31.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator31.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel16.add(jSeparator31);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ingrese la Fecha de la Venta (AAAA-MM-DD)");
        jPanel16.add(jLabel8);

        jSeparator32.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator32.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator32.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel16.add(jSeparator32);

        seccionFechaCliente.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(220, 220, 180));
        jPanel17.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator33.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator33.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator33.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel17.add(jSeparator33);

        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setForeground(new java.awt.Color(0, 0, 0));
        jTextField7.setText("Ingrese el texto aquí");
        jTextField7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField7.setMaximumSize(new java.awt.Dimension(500, 40));
        jTextField7.setPreferredSize(new java.awt.Dimension(50, 26));
        jPanel17.add(jTextField7);

        seccionFechaCliente.add(jPanel17);

        jSeparator34.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator34.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator34.setMaximumSize(new java.awt.Dimension(32767, 10));
        seccionFechaCliente.add(jSeparator34);

        jPanel18.setBackground(new java.awt.Color(220, 220, 180));
        jPanel18.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator35.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator35.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator35.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel18.add(jSeparator35);

        jSeparator36.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator36.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator36.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel18.add(jSeparator36);

        seccionFechaCliente.add(jPanel18);

        jSeparator40.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator40.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator40.setMaximumSize(new java.awt.Dimension(32767, 10));
        seccionFechaCliente.add(jSeparator40);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("SIGUIENTE");
        jButton3.setAlignmentX(0.5F);
        jButton3.setAlignmentY(1.0F);
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(200, 50));
        jButton3.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        seccionFechaCliente.add(jButton3);

        getContentPane().add(seccionFechaCliente, "card2");

        seccionCarritoCompras.setBackground(new java.awt.Color(220, 220, 180));
        seccionCarritoCompras.setMaximumSize(new java.awt.Dimension(640, 420));
        seccionCarritoCompras.setMinimumSize(new java.awt.Dimension(100, 100));
        seccionCarritoCompras.setPreferredSize(new java.awt.Dimension(640, 420));
        seccionCarritoCompras.setLayout(new javax.swing.BoxLayout(seccionCarritoCompras, javax.swing.BoxLayout.Y_AXIS));

        jSeparator3.setForeground(java.awt.Color.darkGray);
        jSeparator3.setMaximumSize(new java.awt.Dimension(32767, 20));
        seccionCarritoCompras.add(jSeparator3);

        jPanel3.setBackground(new java.awt.Color(220, 220, 180));
        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator9.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator9.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator9.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel3.add(jSeparator9);

        jSeparator12.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator12.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator12.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel3.add(jSeparator12);

        seccionCarritoCompras.add(jPanel3);

        jSeparator4.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator4.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator4.setMaximumSize(new java.awt.Dimension(32767, 10));
        seccionCarritoCompras.add(jSeparator4);

        jPanel5.setBackground(new java.awt.Color(220, 220, 180));
        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator11.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator11.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator11.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel5.add(jSeparator11);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese el Nombre del Producto");
        jPanel5.add(jLabel3);

        jSeparator13.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator13.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator13.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel5.add(jSeparator13);

        seccionCarritoCompras.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(220, 220, 180));
        jPanel6.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator14.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator14.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator14.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel6.add(jSeparator14);

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setText("Ingrese el texto aquí");
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField2.setMaximumSize(new java.awt.Dimension(500, 40));
        jTextField2.setPreferredSize(new java.awt.Dimension(50, 26));
        jPanel6.add(jTextField2);

        seccionCarritoCompras.add(jPanel6);

        jSeparator5.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator5.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator5.setMaximumSize(new java.awt.Dimension(32767, 10));
        seccionCarritoCompras.add(jSeparator5);

        jPanel7.setBackground(new java.awt.Color(220, 220, 180));
        jPanel7.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator15.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator15.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator15.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel7.add(jSeparator15);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ingrese la cantidad que desea comprar");
        jPanel7.add(jLabel4);

        jSeparator16.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator16.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator16.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel7.add(jSeparator16);

        seccionCarritoCompras.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(220, 220, 180));
        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator17.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator17.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator17.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel8.add(jSeparator17);

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setText("Ingrese el texto aquí");
        jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField3.setMaximumSize(new java.awt.Dimension(500, 40));
        jTextField3.setPreferredSize(new java.awt.Dimension(50, 26));
        jPanel8.add(jTextField3);

        seccionCarritoCompras.add(jPanel8);

        jPanel10.setBackground(new java.awt.Color(220, 220, 180));
        jPanel10.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator19.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator19.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator19.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel10.add(jSeparator19);

        jSeparator20.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator20.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator20.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel10.add(jSeparator20);

        jPanel12.setBackground(new java.awt.Color(220, 220, 180));
        jPanel12.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator24.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator24.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator24.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel12.add(jSeparator24);

        jPanel10.add(jPanel12);

        seccionCarritoCompras.add(jPanel10);

        jSeparator7.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator7.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator7.setMaximumSize(new java.awt.Dimension(32767, 10));
        seccionCarritoCompras.add(jSeparator7);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("AGREGAR OTRO PRODUCTO AL CARRITO");
        jButton2.setAlignmentX(0.5F);
        jButton2.setAlignmentY(1.0F);
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(500, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        seccionCarritoCompras.add(jButton2);

        jPanel19.setBackground(new java.awt.Color(220, 220, 180));
        jPanel19.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel19.setLayout(new javax.swing.BoxLayout(jPanel19, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator37.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator37.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator37.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel19.add(jSeparator37);

        seccionCarritoCompras.add(jPanel19);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 102, 102));
        jButton5.setText("FINALIZAR VENTA");
        jButton5.setAlignmentX(0.5F);
        jButton5.setAlignmentY(1.0F);
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setMaximumSize(new java.awt.Dimension(200, 50));
        jButton5.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton5.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        seccionCarritoCompras.add(jButton5);

        getContentPane().add(seccionCarritoCompras, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel seccionCarritoCompras;
    private javax.swing.JPanel seccionFechaCliente;
    // End of variables declaration//GEN-END:variables
}
