/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectovisual.gClientes;

import com.mycompany.proyectovisual.gVentas.*;
import fiuni.edu.py.Controladores.ControladorVentas;
import fiuni.edu.py.Modelo.Ventas;
import java.util.List;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 * Clase que representa la ventana de lista de ventas eliminadas. Muestra en una
 * tabla todas las ventas que han sido eliminadas previamente, incluyendo su ID,
 * fecha, cliente, cantidad de ítems y total.
 *
 * Utiliza un controlador para obtener los datos y seguir el patrón MVC.
 *
 * @author luisf
 */
public class ListaVentasPorCliente extends javax.swing.JFrame {

    // Controlador que maneja las operaciones relacionadas a ventas eliminadas
    private final ControladorVentas controlador = new ControladorVentas();
    private int id;
    
    /**
     * Constructor de la clase. Inicializa los componentes gráficos de la
     * ventana, la centra en pantalla y llama al método para listar las ventas
     * eliminadas.
     */
    public ListaVentasPorCliente(int id) {
        this.id=id;
        initComponents();
        setLocationRelativeTo(null);
        listar();
    }
     public ListaVentasPorCliente() {
        initComponents();
        setLocationRelativeTo(null); 
    }

    /**
     * Lista todas las ventas eliminadas en la tabla de la interfaz gráfica.
     * Obtiene los datos a través del controlador y los carga en el modelo de la
     * tabla. Si ocurre un error al cargar una venta, se muestra un mensaje al
     * usuario.
     */
    public void listar() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        List<Ventas> ventas = controlador.listarVentas();
        
        boolean encontrado = false;

    for (Ventas v : ventas) {
        if (v.getIdCliente() == id) {
            modelo.addRow(new Object[]{
                v.getIdVenta(),
                v.getFechaVenta(),
                v.getIdCliente(),
                v.getItems().size(),
                controlador.calcularTotalVenta(v)
            });
            encontrado = true;
        }
    }

        if (!encontrado) {
        JOptionPane.showMessageDialog(this,"No se encontraron ventas para el cliente con ID: " + id);
         new MenuGestionVentas().setVisible(true);
        dispose();
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(220, 220, 180));
        setMinimumSize(new java.awt.Dimension(640, 420));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(5, 0));

        jPanel1.setBackground(new java.awt.Color(220, 220, 180));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 112));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("LISTA DE VENTAS POR CLIENTE");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2);

        jSeparator3.setForeground(java.awt.Color.darkGray);
        jSeparator3.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel1.add(jSeparator3);

        jPanel4.setBackground(new java.awt.Color(220, 220, 180));
        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 400));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator10.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator10.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator10.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel4.add(jSeparator10);

        jSeparator7.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator7.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator7.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanel4.add(jSeparator7);

        jPanel2.setBackground(new java.awt.Color(220, 220, 180));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
        jPanel4.add(jPanel2);

        jSeparator8.setBackground(new java.awt.Color(220, 220, 180));
        jSeparator8.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator8.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanel4.add(jSeparator8);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(450, 32767));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha", "Cliente", "Productos", "Total"
            }
        ));
        jTable1.setAlignmentX(0.0F);
        jTable1.setAlignmentY(0.0F);
        jTable1.setMaximumSize(new java.awt.Dimension(600, 70));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1);

        jPanel1.add(jPanel4);

        jSeparator5.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator5.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel1.add(jSeparator5);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("VOLVER");
        jButton3.setAlignmentX(0.5F);
        jButton3.setAlignmentY(1.0F);
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(200, 50));
        jButton3.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jSeparator6.setForeground(new java.awt.Color(220, 220, 180));
        jSeparator6.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel1.add(jSeparator6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción que se ejecuta al presionar el botón de regreso al menú de gestión
     * de ventas. Abre la ventana de gestión de ventas y cierra la actual.
     *
     * @param evt Evento de acción generado al presionar el botón.
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new MenuGestionVentas().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
